USE hospital;

-- #1 List all patients along with their gender and registration date.
SELECT  patient_id,
		first_name, 
        last_name,
        gender,
        registration_date
FROM patients;


-- #2 Show all doctors and their specializations.
SELECT  doctor_id,
		first_name,
        last_name,
        specialization
FROM doctors;


-- #3 Count the total number of appointments in the system.
SELECT COUNT(*) AS no_of_appointments
FROM appointments;


-- #4 Find all appointments scheduled for a specific date (2023-10-19).
SELECT *
FROM appointments
WHERE appointment_date = '2023-08-19';


-- #5 Retrieve patient details for a given appointment (A100).
SELECT  a.appointment_id,
		a.appointment_date,
        a.reason_for_visit,
        a.status,
		p.patient_id,
        p.first_name,
        p.last_name,
        p.gender,
        p.date_of_birth,
        p.contact_number
FROM appointments a
LEFT JOIN patients p
	ON a.patient_id = p.patient_id
WHERE a.appointment_id = "A100";


-- #6 Get the list of treatments performed along with their costs.
SELECT  treatment_id,
		treatment_type,
        description,
        cost
FROM treatments;


-- #7 Count the number of patients by gender.
SELECT  gender,
		COUNT(*) AS total_patients
FROM patients
GROUP BY gender;


-- #8 Show the total billing amount per payment method. 
SELECT 	payment_method,
		SUM(amount) AS total_amount
FROM billings
GROUP BY payment_method;


-- #9 Find the number of appointments each doctor handled.
SELECT  d.doctor_id,
		CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
		COUNT(a.appointment_id) AS no_of_appointments
FROM doctors d
LEFT JOIN appointments a
	ON d.doctor_id = a.doctor_id
GROUP BY doctor_id;


-- #10 Identify the most common reason for visit in appointments.
SELECT  reason_for_visit,
		COUNT(*) as total_visits
FROM appointments
GROUP BY reason_for_visit
ORDER BY total_visits desc
LIMIT 1;


-- #11 Calculate the average treatment cost.
SELECT ROUND( AVG(cost), 2) AS avg_treatment_cost
FROM treatments;


-- #12 Get total revenue generated.
SELECT ROUND(SUM(amount), 2) AS total_revenue
FROM billings;


-- #13 List patients who have taken more than one treatment.
SELECT  p.patient_id,
		CONCAT (p.first_name, ' ', p.last_name) AS patient_name,
        COUNT(t.treatment_id) AS total_treatments
FROM patients p
JOIN appointments a
	ON p.patient_id = a.patient_id
JOIN treatments t
	ON a.appointment_id = t.appointment_id
GROUP BY p.patient_id, patient_name
HAVING COUNT(t.treatment_id) > 1;


-- #14 Find the doctor with the highest years of experience.
SELECT  doctor_id,
		CONCAT (first_name, ' ', last_name) AS doctor_name,
        years_experience
FROM doctors
GROUP BY doctor_id
ORDER BY years_experience DESC
LIMIT 1;


#15 Calculate the age of each patient.
SELECT  patient_id,
		CONCAT (first_name, ' ', last_name) AS patient_name,
        TIMESTAMPDIFF(YEAR, date_of_birth, CURDATE()) AS patient_age
FROM patients;


-- #16 List treatments where the cost is above the overall average cost.
SELECT  treatment_id,
		treatment_type,
		cost
FROM treatments
WHERE cost > (SELECT AVG(cost) FROM treatments);


-- #17 Calculate the average number of days between a patient’s registration date and their first appointment.
WITH first_appointment AS (
	SELECT 
		p.patient_id,
		p.registration_date,
		MIN(a.appointment_date) AS first_visit_date
	FROM patients p
	LEFT JOIN appointments a
		ON p.patient_id = a.patient_id
	GROUP BY p.patient_id, p.registration_date
)
SELECT 
	AVG(DATEDIFF(first_visit_date, registration_date)) AS avg_days_to_first_appointment
FROM first_appointment;


-- #18 Create a full appointment → treatment → billing pipeline view.
CREATE VIEW appointment_treatment_billing AS
SELECT	
	a.appointment_id,
	a.patient_id,
	a.doctor_id,
	a.appointment_date,
	a.appointment_time,
	a.reason_for_visit,
	a.status AS appointment_status,
    
    t.treatment_id,
    t.treatment_type,
    t.description AS treatment_description,
    t.cost AS treatment_cost,
    t.treatment_date,

	b.bill_id,
    b.bill_date,
    b.amount AS bill_amount,
    b.payment_method,
    b.payment_status
    
FROM appointments a
LEFT JOIN treatments t
	ON a.appointment_id = t.appointment_id
LEFT JOIN billings b
	ON t.treatment_id = b.treatment_id;

-- #19 Calculate revenue generated by each doctor.
SELECT 
	d.doctor_id,
	CONCAT (d.first_name, ' ', d.last_name) AS doctor_name,
    SUM(b.amount) as revenue
FROM doctors d
LEFT JOIN appointments a
	ON d.doctor_id = a.doctor_id
LEFT JOIN treatments t
	ON a.appointment_id = t.appointment_id
LEFT JOIN billings b 
	ON a.patient_id = b.patient_id
GROUP BY d.doctor_id, doctor_name;

-- #20 Rank doctors by number of completed appointments.
SELECT 
	d.doctor_id,
    CONCAT(d.first_name, ' ', d.last_name) AS doctor_name,
	COUNT(a.appointment_id) AS completed_appointments,
    RANK() OVER (ORDER BY COUNT(a.appointment_id) DESC) AS doctor_rank
FROM doctors d
JOIN appointments a
	ON d.doctor_id = a.doctor_id
WHERE a.status = 'Completed'
GROUP BY d.doctor_id, doctor_name;

-- #21 Find patients who visited more than 3 times in the last 6 months of 2023.
SELECT 
	p.patient_id,
    CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
    COUNT(a.appointment_id) AS visit_count
FROM patients p
JOIN appointments a
	ON p.patient_id = a.patient_id
WHERE a.appointment_date BETWEEN '2023-07-01' AND '2023-12-31'
GROUP BY patient_id
HAVING visit_count > 3
ORDER BY patient_id, patient_name;

-- #22 Identify the most expensive treatment type per doctor.
SELECT
	doctor_id,
    treatment_type,
    cost
FROM (
	SELECT 
		t.treatment_type,
		t.cost,
		a.doctor_id,
		ROW_NUMBER() OVER (PARTITION BY a.doctor_id ORDER BY t.cost DESC) AS rn
	FROM treatments t
	LEFT JOIN appointments a
		ON t.appointment_id = a.appointment_id
) ranked
WHERE rn = 1;

-- #23 Calculate patient lifetime value: Total amount paid by each patient.
SELECT 
	p.patient_id,
    CONCAT(p.first_name, ' ', p.last_name) AS patient_name,
    COALESCE(SUM(b.amount), 0) as total_amount
FROM patients p
LEFT JOIN appointments a
	ON p.patient_id = a.patient_id
LEFT JOIN treatments t
	ON a.appointment_id = t.appointment_id
LEFT JOIN billings b
	ON t.treatment_id = b.treatment_id
GROUP BY patient_id, patient_name
ORDER BY total_amount DESC;

-- #24 Calculate branch-wise revenue across hospital branches.
SELECT
	d.hospital_branch,
    COALESCE(SUM(b.amount), 0) AS total_revenue
FROM doctors d
JOIN appointments a
	ON d.doctor_id = a.doctor_id
JOIN treatments t
	ON t.appointment_id = a.appointment_id
JOIN billings b
	ON b.treatment_id = t.treatment_id
GROUP BY d.hospital_branch
ORDER BY total_revenue DESC;

-- #25 Compute appointment status conversion rates: Completion rate, Cancellation rate, No-show rate.
SELECT
	COUNT(*) AS total_appointments,
    ROUND(AVG(CASE WHEN status = 'Completed' THEN 1 ELSE 0 END) * 100, 2) AS completion_rate,
    ROUND(AVG(CASE WHEN status = 'Cancelled' THEN 1 ELSE 0 END) * 100, 2) AS cancellation_rate,
	ROUND(AVG(CASE WHEN status = 'No-Show' THEN 1 ELSE 0 END) * 100, 2) AS no_show_rate
FROM appointments;
